# Generated by Django 5.1.1 on 2024-10-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0002_accessrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
