# Generated by Django 5.1.2 on 2024-10-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='tieu de mac dinh', max_length=255),
            preserve_default=False,
        ),
    ]
