# Generated by Django 5.1.1 on 2024-10-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0008_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
