# Generated by Django 5.1.1 on 2024-10-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0012_postaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], default='Asia', max_length=20),
        ),
    ]
